[tool.poetry]
name = "nbswave"
version = "0.4.0"
description = "An utility to render note block songs to a variety of audio formats"
authors = ["Bentroen <bemcdc@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Bentroen/nbswave"
repository = "https://github.com/Bentroen/nbswave"
keywords = ["minecraft", "note-block-studio", "noteblock", "nbs", "audio"]
include = [
     "LICENSE",
]
packages = [
     { include = "nbswave" },
]

[tool.poetry.dependencies]
python = ">=3.11, <3.15"
pynbs = "^1.1.0"
numpy = "^2.4.0"
soundfile = "^0.14.0"
samplerate = "^0.2.4"
pedalboard = { version = "^0.9.17", optional = true }
pyloudnorm = { version = "^0.1.1", optional = true }

[tool.poetry.extras]
effects = ["pedalboard", "pyloudnorm"]

[tool.poetry.group.dev.dependencies]
black = "^22.6.0"
isort = "^5.10.1"
snakeviz = "^2.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
